### ISSUE TITLE
Unable to import python module

### ISSUE THREAD

**Issue by hackmyl1fe** [exmac/tribus-hash#1]
I've been trying to import this module after i've installed it but am constantly getting "Failed to load application: No module named tribus-hash".

I've tried "tribus_hash", "tribus_hashs", "tribus"

running "pip freeze" shows that it is installed (tribus-hashs==1.0)

So im wondering if im just not importing the module properly, or not using the right name for it.

**Comment by exmac** [comment]
looks like fixed, 
now is correct name: tribus-hash

also tested 
https://github.com/exmac/GenesisH0
with this:

python genesis.py -a tribus -z "Wired 09/Jan/2014 The Grand Experiment Goes Live: Overstock.com Is Now Accepting Bitcoins"

result: 
04ffff001d01044c5957697265642030392f4a616e2f3230313420546865204772616e64204578706572696d656e7420476f6573204c6976653a204f76657273746f636b2e636f6d204973204e6f7720416363657074696e6720426974636f696e73
algorithm: tribus
merkle hash: 2f5f1621073cfb875c9028bc67f8c110e1baccd5574aee19c5830a7c5e0af605
pszTimestamp: Wired 09/Jan/2014 The Grand Experiment Goes Live: Overstock.com Is Now Accepting Bitcoins
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
time: 1497712877
bits: 0x1e0ffff0
Searching for genesis hash..
genesis hash found!
nonce: 167153
genesis hash: 00000f03023c7997d863cb8b611de245e955929869e530c70e61db00fb4eb7bf

so, for now - working stage.
thanks for comment
